name: ci

on:
  #push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v6
      - 
        name: Login to ECR
        uses: docker/login-action@v4
        with:
          registry: ${{vars.AWS_ACCOUNT_NUMBER}}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com
          username: ${{ vars.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: front
          push: true
          tags: ${{vars.AWS_ACCOUNT_NUMBER}}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com/chat-app/front:${{github.sha}}